version: 2

sources:
  - name: demo
    database: demo
    schema: demo_schema
    tables:
      - name: bike
      - name: weather

  - name: us_crime
    database: us_crime
    schema: cybersyn
    tables:
      - name: URBAN_CRIME_INCIDENT_LOG